### ISSUE TITLE
Location of configuration file(s) in the file system

### ISSUE THREAD

**Issue by kairuku** [dfaust/soundkonverter#62]
I'm trying to find my old settings so that I can restore them with a new Plasma install.

**Comment by dfaust** [comment]
soundkonverter 2.x:
config file: `~/.kde4/share/config/soundkonverterrc`
data dir: `~/.kde4/share/apps/soundkonverter`
service menus: `~/.kde4/share/kde4/services/ServiceMenus/add_replaygain_with_soundkonverter.desktop`, `~/.kde4/share/kde4/services/ServiceMenus/convert_with_soundkonverter.desktop`

The local prefix (~/.kde4) can be different on some systems, use `kde4-config --localprefix` to get it.

soundkonverter 3.x:
config file: `~/.config/soundkonverterrc`
data dir: `~/.local/share/soundkonverter`
service menus: `~/.local/share/kservices5/ServiceMenus/add_replaygain_with_soundkonverter.desktop`, `~/.local/share/kservices5/ServiceMenus/convert_with_soundkonverter.desktop`

**Comment by kairuku** [comment]
Thanks
