### ISSUE TITLE
3.0.1 Replay Gain Tool - how to start?

### ISSUE THREAD

**Issue by kokosowy** [dfaust/soundkonverter#70]
Hi!

Well, there's a bug or I'm missing something..

I can add files to recalculation I can see buttons for tagging, for close, checkbox to recalculate but I can't find any way to start gain recalculation.. Please help. :-) Thanks!
![zrzut ekranu z 2018-07-27 08-24-52](https://user-images.githubusercontent.com/7746083/43305050-92e39840-9176-11e8-807a-90203fcc1ab4.png)

I use a ready package:
Package: soundkonverter
Architecture: amd64
Version: 3.0.1-1
Priority: optional
Section: universe/kde
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian KDE Extras Team <pkg-kde-extras@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 4105
Depends: kio, libc6 (>= 2.14), libcdparanoia0 (>= 3.10.2+debian), libkf5cddb5, libkf5completion5 (>= 4.97.0), libkf5configcore5 (>= 4.97.0), libkf5configwidgets5 (>= 4.96.0), libkf5coreaddons5 (>= 4.99.0), libkf5i18n5 (>= 4.97.0), libkf5kdelibs4support5 (>= 5.13.0), libkf5kiocore5 (>= 4.96.0), libkf5kiowidgets5 (>= 4.96.0), libkf5notifications5 (>= 4.96.0), libkf5service-bin, libkf5service5 (>= 4.99.0), libkf5solid5 (>= 4.97.0), libkf5textwidgets5 (>= 4.96.0), libkf5widgetsaddons5 (>= 5.1.0), libkf5xmlgui-bin, libkf5xmlgui5 (>= 4.98.0), libphonon4qt5-4 (>= 4:4.8.0), libqt5core5a (>= 5.9.0~beta), libqt5gui5 (>= 5.2.0), libqt5widgets5 (>= 5.2.0~alpha1), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 4.6), libtag1v5 (>= 1.11), phonon4qt5
Recommends: cdparanoia, faad, ffmpeg, flac, kio-audiocd, mp3gain, mplayer, mppenc, speex, timidity, vorbis-tools, vorbisgain, wavpack
Filename: pool/universe/s/soundkonverter/soundkonverter_3.0.1-1_amd64.deb
Size: 729476
MD5sum: 3f849f996951cab1d3b7a6392d3d93de
SHA1: a984a8641f1efaf6a2a73f7ac9d83e6b2102ec2b
SHA256: 941f8636eaadd664b65d046aef02b9e939b1daa5f933dad9e357e602aaf50f0a
Homepage: https://github.com/HessiJames/soundkonverter
Description-en: audio converter frontend for KDE
 soundKonverter is a frontend to various audio converters.
 .
 The key features are:
  - Audio conversion
  - Replay Gain calculation
  - CD ripping
 .
 soundKonverter supports reading and writing tags for many formats, so the tags
 are preserved when converting files.
 .
 See README.Debian for more information on supported formats.
Description-md5: 5feaa999e0289f4f91087d2a8c72f280
Supported: 3y

**Comment by sjconstantin** [comment]
Having the same issue. I can't find the logs to determine root cause

**Comment by mshmm** [comment]
Same issue here when adding folders. Adding files works and calculates Replay Gain.

**Comment by sjconstantin** [comment]
Thanks for the tip @mshmm that resolved the issue for me.  I'm trying to build form source so I can attempt to figure out root cause, but I'm not having much luck.

**Comment by dfaust** [comment]
Thanks for reporting this issue and thanks to @mshmm for trying to solve it. It turned out to be a bug I already fixed in a different location a while back.
I'll try to release a new version soon.

**Comment by kokosowy** [comment]
Yeey! Thank you so much, you rock! I hope the updated package will be there too.
