### ISSUE TITLE
How do we switch the language in the help option?

### ISSUE THREAD

**Issue by phd21** [dfaust/soundkonverter#79]
Hi dfaust,

Thank you for this wonderful application. I have been using this for years now.

How do we switch the language in the help option?

Best regards,
Phil (phd21)

**Comment by mihkel-t** [comment]
This should get fixed by https://github.com/dfaust/soundkonverter/pull/84

**Comment by dfaust** [comment]
Alright, I will close this issue then. Thanks again @mihkel-t .
